const STATUS_CERT = {
  STATUS: [0, 1, 2],
  NO_SCORE: 0,
  NO_CERT: 1,
  CERTIFICATED: 2
};

const STATUS_REGISTERED = {
  STATUS: [0, 1, 2],
  UNREGISTERED: 0,
  REGISTERED: 1,
  CERTIFICATED: 2
};

export { STATUS_CERT, STATUS_REGISTERED };
